<?php return array(
    'root' => array(
        'name' => 'catfolders/dennis',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '88753483aa23022179d925aa1c5ea7cb6d33b7b0',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '10quality/php-data-model' => array(
            'pretty_version' => 'v1.0.3',
            'version' => '1.0.3.0',
            'reference' => 'dea1c20d2100478bb7c929322e49f00b20c9d6d8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../10quality/php-data-model',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        '10quality/wp-query-builder' => array(
            'pretty_version' => 'v1.0.13',
            'version' => '1.0.13.0',
            'reference' => '4fab2210761cb321313ac894ce5b64ebaefba328',
            'type' => 'library',
            'install_path' => __DIR__ . '/../10quality/wp-query-builder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'catfolders/dennis' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '88753483aa23022179d925aa1c5ea7cb6d33b7b0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'enshrined/svg-sanitize' => array(
            'pretty_version' => '0.15.4',
            'version' => '0.15.4.0',
            'reference' => 'e50b83a2f1f296ca61394fe88fbfe3e896a84cf4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../enshrined/svg-sanitize',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'maennchen/zipstream-php' => array(
            'pretty_version' => '2.2.6',
            'version' => '2.2.6.0',
            'reference' => '30ad6f93cf3efe4192bc7a4c9cad11ff8f4f237f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maennchen/zipstream-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'myclabs/php-enum' => array(
            'pretty_version' => '1.8.5',
            'version' => '1.8.5.0',
            'reference' => 'e7be26966b7398204a234f8673fdad5ac6277802',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/php-enum',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.1',
            'version' => '1.1.0.0',
            'reference' => 'cb6ce4845ce34a8ad9e68117c10ee90a29919eba',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => '6d857f4d76bd4b343eac26d6b539585d2bc56493',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
